# Site settings
title: JVM-NET
header-img: img/bg.jpg
email: jan@jvm-net.com
copyright_name: JVM-NET
description: "A personal blog containing insights and custom creations on the Microsoft Cloud Platform"
baseurl: ""
url: "http://www.jvm-net.com"
twitter_username: JanVanMeirvenne
github_username:  JanVanMeirvenne
facebook_username:  jan.vanmeirvenne.5
email_username:  jan@jvm-net.com
linkedin_profile: https://be.linkedin.com/in/jan-van-meirvenne-6a800b10

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]